#!/bin/env bash

# [version 1.2]

# sosinfo - Archey-like system information tool for StotinkaOS.

# Copyright (C) 2015-2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Variables
PROG="${0##*/}"
user="$(whoami)"
distro="StotinkaOS $(uname -m)";
hostname="$(uname -n)";
kernel="$(uname -r)";
uptime="$(uptime | sed 's/.*up \([^,]*\), .*/\1/')";
shell="${SHELL#/*/*}";
terminal="$TERM";
packages="$(rpm -qa | wc -l)";
cpu="$(cat /proc/cpuinfo | grep 'model name' | cut -f 2 -d ':' | sed -n '1p' | sed 's/CPU //;')";
ram="$(free -m | sed -n '2p' | awk '{print $3"M / "$2"M"}')";

usage(){
cat <<EOF
  usage: $PROG [options] <argv>...

  Options:
     -c, --color
     -h, --help
EOF
  exit 0
}

# from @@iEFdev Archey-OS-X
# Function _disk()
# ------------------------------------------------------------
# Display: used/N% of total (N available) (disk)
#
disk() {
  if [[ $diskWarning == 0 ]]; then
    # Without colors...
    disk=`df -Hl | head -2 | tail -1 | awk '{print $3"/"$5 " of " $2 " (" $4 " available) (" $1 ")"}'  | sed 's/\/dev\///g'`;
  else
    # DiskWarning will show some red text when the space
    # left on disk is below the setting.

    # used size
    uSize=`df -Hl | head -2 | tail -1 | awk '{ print $3}'`;

    # used size (%)
    pSize=`df -Hl | head -2 | tail -1 | awk '{ print $5}'`;

    # total size
    totSize=`df -Hl | head -2 | tail -1 | awk '{ printf "of %-1s", $2}'`;

    # available size
    aSize=`df -Hl | head -2 | tail -1 | awk '{ printf "(%-1s available)", $4}'`;

    # diskNsN
    mPoint=`df -Hl | head -2 | tail -1 | awk '{printf "(%-1s)", $1}'  | sed 's/\/dev\///g'`;

    # Sum up ...
    disk="$uSize/$pSize $totSize $aSize $mPoint";
  fi
}
disk;

# Command line options
for arg in "$@"; do
  case "${arg}" in
    -c|--color)
      yellow='\e[1;33m'
      purple='\e[1;35m'
      blue='\e[1;34m'
      green='\e[1;32m'
      end='\e[0m'
      ;;
    -h|--help)
      usage;
      ;;
    *)
      echo "Unknown argument: $1" 1>&2
      echo "Use: $0 --help" 1>&2
      exit 1
      ;;
  esac
done

# Logo
echo -e "
                  ${purple}..${end}
          ${green}..',,,. ${purple}:kkxoc,.${end}
       ${green}.,,,,,,,,. ${purple}:kkkkkkkxc.${end}
     ${green}',,,,,,,,,,. ${purple};xkkkkkkkkko.      ${blue}User:${end} $user
   ${green}.,,,,,,,..        ${purple}.,lxkkkkkkc     ${blue}Hostname:${end} $hostname
  ${green}',,,,,,.    ${blue}.;ccc:;.   ${purple};xkkkkko    ${blue}Distro:${end} $distro
 ${green}.,,,,,'    ${blue}.k0kc;;:lo    ${purple}.dkkkkkl   ${blue}Kernel:${end} $kernel
${green}.,,,,,,     ${blue}c00'           ${purple}.xkkkkk.  ${blue}Uptime:${end} $uptime
 ${green}......     ${blue}.k00dl:,.       ${purple},:::::.  ${blue}Shell:${end} $shell
${green}'ccccc;       ${blue}.';coO0O.     ${purple}......   ${blue}Terminal:${end} $terminal
${blue}'000000.           ${blue}.00c     ${yellow},,,,,,   ${blue}Packages:${end} $packages
 ${blue}d00000k.   ${blue};oc:;:lk0k.    ${yellow}',,,,,.   ${blue}CPU:${end} $cpu
  ${blue}x000000:  ${blue}.,:ccc:,.    ${yellow}.,,,,,,'    ${blue}Memory:${end} $ram
   ${blue}o0000000o;.        ${yellow}..,,,,,,,.     ${blue}Disk:${end} $disk
    ${blue}.x000000000O: ${yellow}.',,,,,,,,,'${end}
      ${blue}.lO0000000c ${yellow}.,,,,,,,'.${end}
         ${blue}.;lxO00c ${yellow}.,,''..${end}
              ${blue}...${end}
"
