#!/bin/env bash

# [version 1.2]

# sosinfo - Archey-like system information tool for StotinkaOS.

# Copyright (C) 2015-2016 StotinkaOS Team <stotinkaos.bg@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Variables
PROG="${0##*/}"
user="$(whoami)"
distro="StotinkaOS $(cat /etc/centos-release | sed 's/^.*release //;s/ (Fin.*$//')";
hostname="$(uname -n)";
kernel="$(uname -r)";
de="$DESKTOP_SESSION"
uptime="$(uptime | sed 's/.*up \([^,]*\), .*/\1/')";
shell="${SHELL#/*/*}";
terminal="$TERM";
packages="$(rpm -qa | wc -l)";
cpu="$(cat /proc/cpuinfo | grep 'model name' | cut -f 2 -d ':' | sed -n '1p' | sed 's/CPU //;')";
ram="$(free -m | sed -n '2p' | awk '{print $3"M / "$2"M"}')";
disk="$(df -Tlh --total -t ext4 -t ext3 -t xfs --block-size=GB | head -2 | tail -1 | awk '{print $4"/"$3 " от " $2 " (" $5 " свободни) (" $1 ")"}' | sed 's/\/dev\///g')"
resolution="$(xrandr --current | grep  '*' | uniq | awk '{print $1}')"

usage(){
cat <<EOF
  usage: $PROG [options] <argv>...

  Options:
     -c, --color
     -h, --help
EOF
  exit 0
}

# Command line options
for arg in "$@"; do
  case "${arg}" in
    -c|--color)
      yellow='\e[1;33m'
      purple='\e[1;35m'
      blue='\e[1;34m'
      green='\e[1;32m'
      end='\e[0m'
      ;;
    -h|--help)
      usage;
      ;;
    *)
      echo "Unknown argument: $1" 1>&2
      echo "Use: $0 --help" 1>&2
      exit 1
      ;;
  esac
done

# Logo
echo -e "
              ${blue}.............${end}
          ${blue}.....................${end}
        ${blue}...........................${end}
      ${blue}.........${end}${yellow},codxxxxxdl:,${end}${blue}.........${end}     ${blue}User:${end} $user
     ${blue}.......${end}${yellow},lkkkxlc;;;:ccodxl'${end}${blue}.......${end}    ${blue}Hostname:${end} $hostname
    ${blue}......${end}${yellow}'okkkd.${end}             ${blue}.........${end}   ${blue}Distro:${end} $distro
   ${blue}......${end}${yellow}'kkkkk'${end}                 ${blue}.......${end}  ${blue}Kernel:${end} $kernel
  ${blue}.......${end} ${yellow}kkkkkl${end}                  ${blue}.......${end} ${blue}Uptime:${end} $uptime
  ${blue}......${end}  ${yellow}:kkkkkxlc;;;;;;;,.${end}      ${blue}.......${end} ${blue}DE:${end} $de
  ${blue}......${end}   ${yellow},xkkkkkkkkkkkkkkkkd;${end}    ${blue}......${end} ${blue}Shell:${end} $shell
  ${blue}......${end}     ${yellow}.;coodkkkkkkkkkkkkx.${end}  ${blue}......${end} ${blue}Resolution:${end} $resolution
  ${blue}.......${end}                 ${yellow}'xkkkko${end}${blue} .......${end} ${blue}Terminal:${end} $terminal
   ${blue}.......${end}                 ${yellow}ckkkkk${end}${blue}.......${end}  ${blue}Packages:${end} $packages
   ${blue}........${end}               ${yellow}.okkkx;${end}${blue}......${end}   ${blue}CPU:${end} $cpu      
     ${blue}.......${end}${yellow}coc:;,.....,;okkkd:${end}${blue}.......${end}    ${blue}Memory:${end} $ram
      ${blue}........${end}${yellow},coxkkkkkkkxoc,${end}${blue}........${end}     ${blue}Disk:${end} $disk
        ${blue}...........${end}${yellow}','''${end}${blue}...........${end}
          ${blue}.......................${end}
             ${blue}................${end}
"
